version: "3"

services:
  database:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER_NAME
    ports:
      - "5432:5432"
    networks:
      - network
      -
networks:
  network:
    driver: bridge
